query GetPostBySlugQuery($host: String!, $slug: String!) {
	publication(host: $host) {
		title
		post(slug: $slug) {
			id
			slug
			title
			seo {
				title
				description
			}
			tags {
				slug
			}
			coverImage {
				url
			}
			content {
				markdown
			}
			features {
				tableOfContents {
					items {
						slug
						title
					}
				}
			}
		}
	}
}
